import type { Metadata } from "next";
import { GeistProvider, CssBaseline } from '@geist-ui/react';
import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientWrapper>
          <Header />

          <main>{children}</main>

          <Toaster position="bottom-center" />
        </ClientWrapper>
      </body>
    </html>
  );
}
